package hr.abc.psd2.model.dto.error;

/**
 * Created by Tomica on 10-Jan-19.
 */
public enum ErrorCode {

    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    BAD_REQUEST("BAD_REQUEST"),
    INVALID_TPP_ROLE("INVALID_TPP_ROLE"),
    NO_PAYMENT_PRODUCT_PARAM("NO_PAYMENT_PRODUCT_PARAM"),
    WRONG_PAYMENT_PRODUCT_PARAM("WRONG_PAYMENT_PRODUCT_PARAM"),
    NOT_SUPPORTED("NOT_SUPPORTED"),
    NO_PAYMENT_ID_PARAM("NO_PAYMENT_ID_PARAM"),
    RESOURCE_UNKNOWN("RESOURCE_UNKNOWN"),
    NOT_FOUND("NOT_FOUND"),
    ACCESS_EXCEEDED ("ACCESS_EXCEEDED"),
    AIS_CONSENT_INVALID("AIS_CONSENT_INVALID"),
    NON_RECURRING_CONSENT_TIMEOUT("NON_RECURRING_CONSENT_TIMEOUT"),
    FORMAT_ERROR("FORMAT_ERROR"),
    PARAMETER_NOT_SUPPORTED("PARAMETER_NOT_SUPPORTED"),
    SERVICE_INVALID("SERVICE_INVALID"),
	REFERENCE_STATUS_INVALID("REFERENCE_STATUS_INVALID"),
    STATUS_INVALID("STATUS_INVALID"),
    RESOURCE_EXPIRED("RESOURCE_EXPIRED"),
    CONSENT_EXPIRED("CONSENT_EXPIRED "),
    REQUESTED_FORMATS_INVALID("REQUESTED_FORMATS_INVALID"),
    PRODUCT_UNKNOWN("PRODUCT_UNKNOWN "),
    EXECUTION_DATE_INVALID("EXECUTION_DATE_INVALID"),
    PAYMENT_FAILED("PAYMENT_FAILED "),
    CANCELLATION_INVALID("CANCELLATION_INVALID"),
    RESOURCE_BLOCKED("RESOURCE_BLOCKED"),


    SIGNATURE_MISSING("SIGNATURE_MISSING"),
    SIGNATURE_INVALID("SIGNATURE_INVALID"),
    CERTIFICATE_MISSING("CERTIFICATE_MISSING"),
    CERTIFICATE_REVOKED("CERTIFICATE_REVOKED"),
    CERTIFICATE_BLOCKED("CERTIFICATE_BLOCKED"),
    CERTIFICATE_EXPIRED("CERTIFICATE_EXPIRED"),
    CERTIFICATE_INVALID("CERTIFICATE_INVALID"),
    CONSENT_UNKNOWN("CONSENT_UNKNOWN");

    private String value;

    ErrorCode(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static ErrorCode getByName(String name) {
        for(ErrorCode e : values()) {
            if(e.value.equals(name)) return e;
        }
        return null;
    }
}
